-- Melbourne CBD Crowd Platform - Supabase schema (run in the SQL editor)
-- Creates all tables the app expects and the RLS policies the anon key needs.
-- Run this on a FRESH Supabase project so the deployed app behaves identically
-- to the developer's project (sensor_locations, hourly_counts, user_sessions).

-- 1) sensor_locations ------------------------------------------------------
create table if not exists public.sensor_locations (
    id bigint generated by default as identity primary key,
    location_id bigint not null unique,
    sensor_description text not null default '',
    sensor_name text not null default '',
    status text not null default 'A',
    latitude double precision not null default 0,
    longitude double precision not null default 0,
    installation_date timestamp default null
);
create index if not exists sensor_locations_location_id_idx on public.sensor_locations (location_id);

alter table public.sensor_locations enable row level security;
drop policy if exists "anon can read sensor_locations" on public.sensor_locations;
create policy "anon can read sensor_locations" on public.sensor_locations
    for select using (true);

-- 2) hourly_counts ---------------------------------------------------------
create table if not exists public.hourly_counts (
    id bigint generated by default as identity primary key,
    location_id bigint not null,
    datetime timestamp not null,
    count double precision not null default 0,
    sensor_name text not null default '',
    unique (location_id, datetime)
);
-- CRITICAL: index makes the recent-window REST queries fast (without it the
-- app's Supabase fetch of the last 45 days times out / takes 20+ seconds).
create index if not exists hourly_counts_loc_datetime_idx on public.hourly_counts (location_id, datetime desc);
create index if not exists hourly_counts_datetime_idx on public.hourly_counts (datetime);

alter table public.hourly_counts enable row level security;
drop policy if exists "anon can read hourly_counts" on public.hourly_counts;
create policy "anon can read hourly_counts" on public.hourly_counts
    for select using (true);

-- 3) user_sessions (anonymous accessibility preferences, no PII) -----------
create table if not exists public.user_sessions (
    session_hash text primary key,
    preferences jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

alter table public.user_sessions enable row level security;
drop policy if exists "anon can select user_sessions" on public.user_sessions;
create policy "anon can select user_sessions" on public.user_sessions
    for select using (true);
drop policy if exists "anon can insert user_sessions" on public.user_sessions;
create policy "anon can insert user_sessions" on public.user_sessions
    for insert with check (true);
drop policy if exists "anon can update user_sessions" on public.user_sessions;
create policy "anon can update user_sessions" on public.user_sessions
    for update using (true) with check (true);

-- Seeding (run after this SQL, from backend/):
--   SUPABASE_URL=https://<project>.supabase.co SUPABASE_KEY=<anon-key> \
--   python scripts/seed_supabase.py            # 134 sensor metadata rows
--   SUPABASE_URL=... SUPABASE_KEY=... \
--   python scripts/seed_supabase_history.py    # real hourly counts (1.6M rows)
